package com.riskengine.unsec_pl.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Phone Number")
	private java.lang.String phone_number;
	@org.kie.api.definition.type.Label("Nationality")
	private java.lang.String nationality;
	@org.kie.api.definition.type.Label("Residence")
	private java.lang.Boolean is_residence;
	@org.kie.api.definition.type.Label("Occupation ID")
	private int occupation_id;

	@org.kie.api.definition.type.Label("Permanent Address")
	private Address permanent_address;

	@org.kie.api.definition.type.Label("Temporary Address")
	private Address temporary_address;

	@org.kie.api.definition.type.Label("Employer Address")
	private Address employer_address;

	@org.kie.api.definition.type.Label("Monthly Income Declared")
	private int monthly_income_declared;

	@org.kie.api.definition.type.Label("Monthly Expense Declared")
	private int monthly_expense_declared;

	@org.kie.api.definition.type.Label("Age - System")
	private int age;

	@org.kie.api.definition.type.Label("Date Of Birth")
	private java.time.LocalDate date_of_birth;

	@org.kie.api.definition.type.Label(value = "Eligible")
	private boolean eligible;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPhone_number() {
		return this.phone_number;
	}

	public void setPhone_number(java.lang.String phone_number) {
		this.phone_number = phone_number;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.Boolean getIs_residence() {
		return this.is_residence;
	}

	public void setIs_residence(java.lang.Boolean is_residence) {
		this.is_residence = is_residence;
	}

	public int getOccupation_id() {
		return this.occupation_id;
	}

	public void setOccupation_id(int occupation_id) {
		this.occupation_id = occupation_id;
	}

	public int getMonthly_income_declared() {
		return this.monthly_income_declared;
	}

	public void setMonthly_income_declared(int monthly_income_declared) {
		this.monthly_income_declared = monthly_income_declared;
	}

	public int getMonthly_expense_declared() {
		return this.monthly_expense_declared;
	}

	public void setMonthly_expense_declared(int monthly_expense_declared) {
		this.monthly_expense_declared = monthly_expense_declared;
	}

	public com.riskengine.unsec_pl.models.Address getPermanent_address() {
		return this.permanent_address;
	}

	public void setPermanent_address(
			com.riskengine.unsec_pl.models.Address permanent_address) {
		this.permanent_address = permanent_address;
	}

	public com.riskengine.unsec_pl.models.Address getTemporary_address() {
		return this.temporary_address;
	}

	public void setTemporary_address(
			com.riskengine.unsec_pl.models.Address temporary_address) {
		this.temporary_address = temporary_address;
	}

	public com.riskengine.unsec_pl.models.Address getEmployer_address() {
		return this.employer_address;
	}

	public void setEmployer_address(
			com.riskengine.unsec_pl.models.Address employer_address) {
		this.employer_address = employer_address;
	}

	public java.time.LocalDate getDate_of_birth() {
		return this.date_of_birth;
	}

	public void setDate_of_birth(java.time.LocalDate date_of_birth) {
		this.date_of_birth = date_of_birth;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public boolean isEligible() {
		return this.eligible;
	}

	public void setEligible(boolean eligible) {
		this.eligible = eligible;
	}

	public Applicant(java.lang.String name, java.lang.String phone_number,
			java.lang.String nationality, java.lang.Boolean is_residence,
			int occupation_id,
			com.riskengine.unsec_pl.models.Address permanent_address,
			com.riskengine.unsec_pl.models.Address temporary_address,
			com.riskengine.unsec_pl.models.Address employer_address,
			int monthly_income_declared, int monthly_expense_declared, int age,
			java.time.LocalDate date_of_birth, boolean eligible) {
		this.name = name;
		this.phone_number = phone_number;
		this.nationality = nationality;
		this.is_residence = is_residence;
		this.occupation_id = occupation_id;
		this.permanent_address = permanent_address;
		this.temporary_address = temporary_address;
		this.employer_address = employer_address;
		this.monthly_income_declared = monthly_income_declared;
		this.monthly_expense_declared = monthly_expense_declared;
		this.age = age;
		this.date_of_birth = date_of_birth;
		this.eligible = eligible;
	}

}