package com.huyhvq.unsec_pl.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Address 1")
	private java.lang.String address_1;
	@org.kie.api.definition.type.Label("Address 2")
	private java.lang.String address_2;
	@org.kie.api.definition.type.Label("City")
	private int city_id;
	@org.kie.api.definition.type.Label("Ward")
	private int ward_id;
	@org.kie.api.definition.type.Label("District")
	private int district_id;

	public Address() {
	}

	public java.lang.String getAddress_1() {
		return this.address_1;
	}

	public void setAddress_1(java.lang.String address_1) {
		this.address_1 = address_1;
	}

	public java.lang.String getAddress_2() {
		return this.address_2;
	}

	public void setAddress_2(java.lang.String address_2) {
		this.address_2 = address_2;
	}

	public int getCity_id() {
		return this.city_id;
	}

	public void setCity_id(int city_id) {
		this.city_id = city_id;
	}

	public int getWard_id() {
		return this.ward_id;
	}

	public void setWard_id(int ward_id) {
		this.ward_id = ward_id;
	}

	public int getDistrict_id() {
		return this.district_id;
	}

	public void setDistrict_id(int district_id) {
		this.district_id = district_id;
	}

	public Address(java.lang.String address_1, java.lang.String address_2,
			int city_id, int ward_id, int district_id) {
		this.address_1 = address_1;
		this.address_2 = address_2;
		this.city_id = city_id;
		this.ward_id = ward_id;
		this.district_id = district_id;
	}

}