package com.huyhvq.unsec_pl.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Request Loan Amount")
	private long amount;
	@org.kie.api.definition.type.Label("Loan Tenor")
	private int tenor;

	@org.kie.api.definition.type.Label("Approved ?")
	private boolean approved;

	@org.kie.api.definition.type.Label("Comment")
	private java.lang.String comment;

	public Loan() {
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public int getTenor() {
		return this.tenor;
	}

	public void setTenor(int tenor) {
		this.tenor = tenor;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public Loan(long amount, int tenor, boolean approved,
			java.lang.String comment) {
		this.amount = amount;
		this.tenor = tenor;
		this.approved = approved;
		this.comment = comment;
	}

}